### ISSUE TITLE
Create cask tap for eap versions

### ISSUE THREAD

**Issue by leipert** [leipert/jetbrains-cask-bot#3]
See this comment https://github.com/caskroom/homebrew-cask/issues/32521#issuecomment-317695166.

If you are interested in a cask-tap that maintains eap versions of jetbrains products, please [file a bounty](https://www.bountysource.com/issues/47595690-create-cask-tap-for-eap-versions) for this issue at bountysource.

My goal is not to get rich, but to get a free pizza and a free beer (for me or someone). So if anyone (or a sum of people) comes up with a minimum of 20€, please post the bounty.

If the bounty is posted, I plan to implement the following features:

- Creation of a jetbrains-eap tap.
- Tap will be maintained by the @jcbot, with the following algorithm:
    1. Assuming a cask named `jetbrains-product-eap` exists
    2. If there is a current eap version, the cask links to the eap version
    3. If not, the cask links to the latest release version

**Comment by leipert** [comment]
Closing due to lack of interest

**Comment by josegonzalez** [comment]
Can this be re-opened? I'd be more than happy to put up the entire bounty so I can manage my goland install via homebrew :)

**Comment by leipert** [comment]
I'll have a look later today, 😄
